version: 0

default_image: earthly/lunar-lib:base-main

name: helm

collectors:
  - name: helm
    description: Collect and validate Helm charts
    mainBash: main.sh 
    hook:
      type: code
